# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Piece-MSSQL
version:      0.01
version_from: lib/Time/Piece/MSSQL.pm
installdirs:  site
requires:
    Test::More:                    0
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
